spring.application.name=aggregate-products-db-service
spring.main.banner-mode=off
server.port=${APP_SERVER_PORT:8082}

logging.level.org.springframework=INFO
spring.codec.max-in-memory-size=2024MB

spring.webflux.base-path=/api/aggregate
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.default-property-inclusion=non_null

management.server.port=8092
management.server.base-path=/
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,prometheus

barcode.error.image.location=/home/paulius/aggregate-products/barcode_error_images
image.base.url=https://foodscan.ai/images/

openfood.http-schema=http
openfood.host=food-scan.main
openfood.port=8080

# OpenAPI endpoints enabled
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger/swagger-ui.html
springdoc.swagger-ui.tagsSorter=alpha
springdoc.api-docs.path=/swagger/api-docs
springdoc.writer-with-order-by-keys=true

# R2DBC configuration Scrapes database
database.host=food-scan.main
database.port=5432
database.name=postgres
database.user=postgres
database.password=postgres
database.schema_name=aggregate

spring.r2dbc.url=r2dbc:postgresql://${database.host}:${database.port}?targetServerType=PRIMARY
spring.r2dbc.name=${database.name}
spring.r2dbc.username=${database.user}
spring.r2dbc.password=${database.password}

# JDBC configuration (requiredd for flyway configuration)
spring.datasource.url=jdbc::postgresql://${database.host}:${database.port}}/${database.name}?currentSchema=${database.schema_name}
spring.datasource.username=${database.user}
spring.datasource.password=${database.password}

# Flyway configuration
spring.flyway.url=jdbc:postgresql://${database.host}:${database.port}/${database.name}
spring.flyway.default-schema=${database.schema_name}
spring.flyway.schemas=${database.schema_name}
spring.flyway.user=${database.user}
spring.flyway.password=${database.password}
spring.flyway.create-schemas=true
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=db.migration

# R2DBC configuration
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20
spring.r2dbc.pool.min-idle=5
